/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from "react";
import { 
  Rocket, 
  Activity, 
  Layers, 
  TrendingUp, 
  DollarSign, 
  Users, 
  HandHeart, 
  Award,
  HelpCircle,
  ArrowUpRight
} from "lucide-react";
import { Startup } from "../../../types";
import { normalizeStage } from "../utils/startupCalculations";
import { useLanguage } from "../../../lib/LanguageContext";

interface StartupKPIsProps {
  startups: Startup[];
}

export default function StartupKPIs({ startups }: StartupKPIsProps) {
  const { t } = useLanguage();
  const totalCount = startups.length;
  
  const activeStartups = startups.filter(s => 
    s.status === "ACCELERATING" || s.status === "ACTIVE" || s.status === "APPLICANT"
  );
  const activeCount = activeStartups.length;

  const mvpEarlyCount = startups.filter(s => {
    const stage = normalizeStage(s.stage);
    return stage === "PRE_MVP" || stage === "MVP" || stage === "IDEA";
  }).length;

  const revenueGeneratingStartups = startups.filter(s => {
    const mrr = s.mrr ?? s.kpis?.mrr ?? 0;
    return (s.revenue > 0 || mrr > 0);
  });
  const revenueGeneratingCount = revenueGeneratingStartups.length;
  const revenueGeneratingPct = totalCount > 0 ? Math.round((revenueGeneratingCount / totalCount) * 100) : 0;

  const totalFunding = startups.reduce((acc, s) => acc + (s.fundingRaised || 0), 0);

  const totalJobsCreated = startups.reduce((acc, s) => {
    return acc + (s.jobsCreated ?? Math.max(0, (s.employees || 1) - 2));
  }, 0);

  const supportedStartups = startups.filter(s => 
    (s.supportHistory && s.supportHistory.length > 0) || 
    s.status === "ACCELERATING" || 
    s.program
  ).length;

  const graduatedOrScaled = startups.filter(s => {
    const stage = normalizeStage(s.stage);
    return stage === "SCALE" || stage === "GRADUATED" || s.status === "GRADUATED";
  }).length;

  const kpis = [
    {
      id: "kpi-total-startups",
      title: t("Total Startups"),
      value: totalCount.toString(),
      subtext: t("Ecosystem pipeline"),
      badge: "+100%",
      badgeColor: "text-emerald-700 bg-emerald-50 border-emerald-200",
      icon: Rocket,
      iconColor: "text-emerald-600 bg-emerald-50",
      tooltip: t("Total number of registered technology startups tracked in Kashkadarya region across all cohorts.")
    },
    {
      id: "kpi-active-startups",
      title: t("Active Startups"),
      value: activeCount.toString(),
      subtext: `${totalCount > 0 ? Math.round((activeCount / totalCount) * 100) : 0}% of cohort`,
      badge: t("Active"),
      badgeColor: "text-indigo-700 bg-indigo-50 border-indigo-200",
      icon: Activity,
      iconColor: "text-indigo-600 bg-indigo-50",
      tooltip: t("Startups currently active in incubation, acceleration, or regular mentorship programs.")
    },
    {
      id: "kpi-mvp-early",
      title: t("MVP / Early Stage"),
      value: mvpEarlyCount.toString(),
      subtext: t("Idea to Prototype"),
      badge: t("In Dev"),
      badgeColor: "text-amber-700 bg-amber-50 border-amber-200",
      icon: Layers,
      iconColor: "text-amber-600 bg-amber-50",
      tooltip: t("Startups currently at Idea, Pre-MVP, or MVP validation stages building initial product versions.")
    },
    {
      id: "kpi-revenue-generating",
      title: t("Revenue Generating"),
      value: revenueGeneratingCount.toString(),
      subtext: `${revenueGeneratingPct}% monetize`,
      badge: t("Monetized"),
      badgeColor: "text-emerald-700 bg-emerald-50 border-emerald-200",
      icon: TrendingUp,
      iconColor: "text-emerald-600 bg-emerald-50",
      tooltip: t("Startups with positive monthly recurring revenue (MRR) or active customer subscriptions.")
    },
    {
      id: "kpi-total-funding",
      title: t("Total Funding"),
      value: `$${(totalFunding / 1000000 >= 1 ? (totalFunding / 1000000).toFixed(1) + "M" : (totalFunding / 1000).toFixed(0) + "K")}`,
      subtext: `$${totalFunding.toLocaleString()} USD`,
      badge: t("Raised"),
      badgeColor: "text-cyan-700 bg-cyan-50 border-cyan-200",
      icon: DollarSign,
      iconColor: "text-cyan-600 bg-cyan-50",
      tooltip: t("Cumulative external funding raised by startups from venture capital, angel syndicates, and government grants.")
    },
    {
      id: "kpi-jobs-created",
      title: t("Jobs Created"),
      value: totalJobsCreated.toString(),
      subtext: t("High-tech positions"),
      badge: t("Employment"),
      badgeColor: "text-blue-700 bg-blue-50 border-blue-200",
      icon: Users,
      iconColor: "text-blue-600 bg-blue-50",
      tooltip: t("Direct software engineering, product, and tech jobs generated by ecosystem startups in Kashkadarya.")
    },
    {
      id: "kpi-supported-startups",
      title: t("Supported Startups"),
      value: supportedStartups.toString(),
      subtext: t("Received CRM support"),
      badge: t("Impacted"),
      badgeColor: "text-purple-700 bg-purple-50 border-purple-200",
      icon: HandHeart,
      iconColor: "text-purple-600 bg-purple-50",
      tooltip: t("Startups that have received direct IT Park assistance: mentorship, investor intros, talent matching, grants, or office space.")
    },
    {
      id: "kpi-graduated-scaled",
      title: t("Graduated / Scaled"),
      value: graduatedOrScaled.toString(),
      subtext: t("Resident & Scaleups"),
      badge: t("Mature"),
      badgeColor: "text-teal-700 bg-teal-50 border-teal-200",
      icon: Award,
      iconColor: "text-teal-600 bg-teal-50",
      tooltip: t("Startups that have successfully graduated into IT Park Resident companies or scaled into regional markets.")
    }
  ];

  return (
    <div id="startup-kpi-summary" className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-8 gap-3">
      {kpis.map((kpi) => {
        const Icon = kpi.icon;
        return (
          <div 
            key={kpi.id} 
            id={kpi.id}
            className="group relative bg-white border border-slate-200 hover:border-indigo-300 rounded-xl p-3.5 flex flex-col justify-between transition-all duration-200 hover:shadow-sm"
          >
            <div>
              <div className="flex items-center justify-between gap-1 mb-2">
                <div className={`p-1.5 rounded-lg ${kpi.iconColor}`}>
                  <Icon className="w-3.5 h-3.5" />
                </div>
                <div className="relative">
                  <div 
                    title={kpi.tooltip}
                    className="text-slate-300 hover:text-slate-500 cursor-help"
                  >
                    <HelpCircle className="w-3 h-3" />
                  </div>
                </div>
              </div>
              <span className="text-[11px] font-semibold text-slate-500 line-clamp-1 block" title={kpi.title}>
                {kpi.title}
              </span>
              <div className="text-lg font-extrabold text-slate-800 font-mono tracking-tight mt-0.5">
                {kpi.value}
              </div>
            </div>

            <div className="mt-2.5 pt-2 border-t border-slate-100 flex items-center justify-between">
              <span className="text-[10px] text-slate-400 truncate max-w-[70%]" title={kpi.subtext}>
                {kpi.subtext}
              </span>
              <span className={`text-[9px] font-bold px-1.5 py-0.2 rounded border ${kpi.badgeColor} shrink-0`}>
                {kpi.badge}
              </span>
            </div>
          </div>
        );
      })}
    </div>
  );
}
